- service_name: app-anbox-stream-gateway
  service_host: "0.0.0.0"
  service_port: 8080
  service_options:
  - mode http
  server_options: check ssl verify none inter 2000 rise 2 fall 5 maxconn 4096
  crts: [DEFAULT]
- service_name: app-anbox-cloud-dashboard
  service_host: "0.0.0.0"
  service_port: 8081
  service_options:
  - mode http
  server_options: check ssl verify none inter 2000 rise 2 fall 5 maxconn 4096
  crts: [DEFAULT]
- service_name: api_http
  service_host: "0.0.0.0"
  service_port: 80
  service_options:
  - mode http
  - http-request redirect scheme https
- service_name: api_https
  service_host: "0.0.0.0"
  service_port: 443
  service_options:
  - mode http
  - balance leastconn
  - acl path_start_api path_beg -i /1.0
  - acl path_start_ui path_beg -i /ui
  - use_backend app-anbox-stream-gateway if path_start_api
  - use_backend app-anbox-stream-gateway if path_start_ui
  - default_backend app-anbox-cloud-dashboard
  crts: [DEFAULT]

